# Generated by Django 5.1.4 on 2024-12-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
